// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.weixin.domain;

import com.ruyicai.weixin.domain.BigUserInfo;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BigUserInfo_Roo_Configurable {
    
    declare @type: BigUserInfo: @Configurable;
    
}
